/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_janelia_simview_lfm_LFMJNI */

#ifndef _Included_org_janelia_simview_lfm_LFMJNI
#define _Included_org_janelia_simview_lfm_LFMJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_janelia_simview_lfm_LFMJNI
 * Method:    jniReadHeader
 * Signature: (Ljava/lang/String;[J[J[F[I[B)I
 */
JNIEXPORT jint JNICALL Java_org_janelia_simview_lfm_LFMJNI_jniReadHeader
  (JNIEnv *, jobject, jstring, jlongArray, jlongArray, jfloatArray, jintArray, jbyteArray);

/*
 * Class:     org_janelia_simview_lfm_LFMJNI
 * Method:    jniReadFull
 * Signature: (Ljava/lang/String;I[B)I
 */
JNIEXPORT jint JNICALL Java_org_janelia_simview_lfm_LFMJNI_jniReadFull__Ljava_lang_String_2I_3B
  (JNIEnv *, jobject, jstring, jint, jbyteArray);

/*
 * Class:     org_janelia_simview_lfm_LFMJNI
 * Method:    jniReadFull
 * Signature: (Ljava/lang/String;I[S)I
 */
JNIEXPORT jint JNICALL Java_org_janelia_simview_lfm_LFMJNI_jniReadFull__Ljava_lang_String_2I_3S
  (JNIEnv *, jobject, jstring, jint, jshortArray);

/*
 * Class:     org_janelia_simview_lfm_LFMJNI
 * Method:    jniReadFull
 * Signature: (Ljava/lang/String;I[I)I
 */
JNIEXPORT jint JNICALL Java_org_janelia_simview_lfm_LFMJNI_jniReadFull__Ljava_lang_String_2I_3I
  (JNIEnv *, jobject, jstring, jint, jintArray);

/*
 * Class:     org_janelia_simview_lfm_LFMJNI
 * Method:    jniReadFull
 * Signature: (Ljava/lang/String;I[J)I
 */
JNIEXPORT jint JNICALL Java_org_janelia_simview_lfm_LFMJNI_jniReadFull__Ljava_lang_String_2I_3J
  (JNIEnv *, jobject, jstring, jint, jlongArray);

/*
 * Class:     org_janelia_simview_lfm_LFMJNI
 * Method:    jniReadFull
 * Signature: (Ljava/lang/String;I[F)I
 */
JNIEXPORT jint JNICALL Java_org_janelia_simview_lfm_LFMJNI_jniReadFull__Ljava_lang_String_2I_3F
  (JNIEnv *, jobject, jstring, jint, jfloatArray);

/*
 * Class:     org_janelia_simview_lfm_LFMJNI
 * Method:    jniReadFull
 * Signature: (Ljava/lang/String;I[D)I
 */
JNIEXPORT jint JNICALL Java_org_janelia_simview_lfm_LFMJNI_jniReadFull__Ljava_lang_String_2I_3D
  (JNIEnv *, jobject, jstring, jint, jdoubleArray);

/*
 * Class:     org_janelia_simview_lfm_LFMJNI
 * Method:    jniReadFull
 * Signature: (Ljava/lang/String;ILjava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_org_janelia_simview_lfm_LFMJNI_jniReadFull__Ljava_lang_String_2ILjava_nio_Buffer_2
  (JNIEnv *, jobject, jstring, jint, jobject);

/*
 * Class:     org_janelia_simview_lfm_LFMJNI
 * Method:    jniReadROI
 * Signature: (Ljava/lang/String;[J[JI[B)I
 */
JNIEXPORT jint JNICALL Java_org_janelia_simview_lfm_LFMJNI_jniReadROI__Ljava_lang_String_2_3J_3JI_3B
  (JNIEnv *, jobject, jstring, jlongArray, jlongArray, jint, jbyteArray);

/*
 * Class:     org_janelia_simview_lfm_LFMJNI
 * Method:    jniReadROI
 * Signature: (Ljava/lang/String;[J[JI[S)I
 */
JNIEXPORT jint JNICALL Java_org_janelia_simview_lfm_LFMJNI_jniReadROI__Ljava_lang_String_2_3J_3JI_3S
  (JNIEnv *, jobject, jstring, jlongArray, jlongArray, jint, jshortArray);

/*
 * Class:     org_janelia_simview_lfm_LFMJNI
 * Method:    jniReadROI
 * Signature: (Ljava/lang/String;[J[JI[I)I
 */
JNIEXPORT jint JNICALL Java_org_janelia_simview_lfm_LFMJNI_jniReadROI__Ljava_lang_String_2_3J_3JI_3I
  (JNIEnv *, jobject, jstring, jlongArray, jlongArray, jint, jintArray);

/*
 * Class:     org_janelia_simview_lfm_LFMJNI
 * Method:    jniReadROI
 * Signature: (Ljava/lang/String;[J[JI[J)I
 */
JNIEXPORT jint JNICALL Java_org_janelia_simview_lfm_LFMJNI_jniReadROI__Ljava_lang_String_2_3J_3JI_3J
  (JNIEnv *, jobject, jstring, jlongArray, jlongArray, jint, jlongArray);

/*
 * Class:     org_janelia_simview_lfm_LFMJNI
 * Method:    jniReadROI
 * Signature: (Ljava/lang/String;[J[JI[F)I
 */
JNIEXPORT jint JNICALL Java_org_janelia_simview_lfm_LFMJNI_jniReadROI__Ljava_lang_String_2_3J_3JI_3F
  (JNIEnv *, jobject, jstring, jlongArray, jlongArray, jint, jfloatArray);

/*
 * Class:     org_janelia_simview_lfm_LFMJNI
 * Method:    jniReadROI
 * Signature: (Ljava/lang/String;[J[JI[D)I
 */
JNIEXPORT jint JNICALL Java_org_janelia_simview_lfm_LFMJNI_jniReadROI__Ljava_lang_String_2_3J_3JI_3D
  (JNIEnv *, jobject, jstring, jlongArray, jlongArray, jint, jdoubleArray);

/*
 * Class:     org_janelia_simview_lfm_LFMJNI
 * Method:    jniReadROI
 * Signature: (Ljava/lang/String;[J[JILjava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_org_janelia_simview_lfm_LFMJNI_jniReadROI__Ljava_lang_String_2_3J_3JILjava_nio_Buffer_2
  (JNIEnv *, jobject, jstring, jlongArray, jlongArray, jint, jobject);

/*
 * Class:     org_janelia_simview_lfm_LFMJNI
 * Method:    jniWriteFull
 * Signature: ([BLjava/lang/String;[JII[F[JI[B)I
 */
JNIEXPORT jint JNICALL Java_org_janelia_simview_lfm_LFMJNI_jniWriteFull___3BLjava_lang_String_2_3JII_3F_3JI_3B
  (JNIEnv *, jobject, jbyteArray, jstring, jlongArray, jint, jint, jfloatArray, jlongArray, jint, jbyteArray);

/*
 * Class:     org_janelia_simview_lfm_LFMJNI
 * Method:    jniWriteFull
 * Signature: ([SLjava/lang/String;[JII[F[JI[B)I
 */
JNIEXPORT jint JNICALL Java_org_janelia_simview_lfm_LFMJNI_jniWriteFull___3SLjava_lang_String_2_3JII_3F_3JI_3B
  (JNIEnv *, jobject, jshortArray, jstring, jlongArray, jint, jint, jfloatArray, jlongArray, jint, jbyteArray);

/*
 * Class:     org_janelia_simview_lfm_LFMJNI
 * Method:    jniWriteFull
 * Signature: ([ILjava/lang/String;[JII[F[JI[B)I
 */
JNIEXPORT jint JNICALL Java_org_janelia_simview_lfm_LFMJNI_jniWriteFull___3ILjava_lang_String_2_3JII_3F_3JI_3B
  (JNIEnv *, jobject, jintArray, jstring, jlongArray, jint, jint, jfloatArray, jlongArray, jint, jbyteArray);

/*
 * Class:     org_janelia_simview_lfm_LFMJNI
 * Method:    jniWriteFull
 * Signature: ([JLjava/lang/String;[JII[F[JI[B)I
 */
JNIEXPORT jint JNICALL Java_org_janelia_simview_lfm_LFMJNI_jniWriteFull___3JLjava_lang_String_2_3JII_3F_3JI_3B
  (JNIEnv *, jobject, jlongArray, jstring, jlongArray, jint, jint, jfloatArray, jlongArray, jint, jbyteArray);

/*
 * Class:     org_janelia_simview_lfm_LFMJNI
 * Method:    jniWriteFull
 * Signature: ([FLjava/lang/String;[JII[F[JI[B)I
 */
JNIEXPORT jint JNICALL Java_org_janelia_simview_lfm_LFMJNI_jniWriteFull___3FLjava_lang_String_2_3JII_3F_3JI_3B
  (JNIEnv *, jobject, jfloatArray, jstring, jlongArray, jint, jint, jfloatArray, jlongArray, jint, jbyteArray);

/*
 * Class:     org_janelia_simview_lfm_LFMJNI
 * Method:    jniWriteFull
 * Signature: ([DLjava/lang/String;[JII[F[JI[B)I
 */
JNIEXPORT jint JNICALL Java_org_janelia_simview_lfm_LFMJNI_jniWriteFull___3DLjava_lang_String_2_3JII_3F_3JI_3B
  (JNIEnv *, jobject, jdoubleArray, jstring, jlongArray, jint, jint, jfloatArray, jlongArray, jint, jbyteArray);

/*
 * Class:     org_janelia_simview_lfm_LFMJNI
 * Method:    jniWriteFull
 * Signature: (Ljava/nio/Buffer;Ljava/lang/String;[JII[F[JI[B)I
 */
JNIEXPORT jint JNICALL Java_org_janelia_simview_lfm_LFMJNI_jniWriteFull__Ljava_nio_Buffer_2Ljava_lang_String_2_3JII_3F_3JI_3B
  (JNIEnv *, jobject, jobject, jstring, jlongArray, jint, jint, jfloatArray, jlongArray, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
